application: internet-technologies-iu-a2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /bootstrap
  static_dir: bootstrap

- url: /store_post
  script: Board.Posts.application
  login: required

- url: /newpost
  script: Board.Posts.application
  login: required

- url: /likesmanager
  script: Board.LikesManager.application
  login: required
- url: /likecomment
  script: Board.LikesManager.application
  login: required

- url: /comment
  script: Board.Posts.application
  login: required

- url: /delete
  script: Board.Posts.application
  login: required

- url: .*
  script: Board.HomePage.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
